import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend, Cell } from "recharts";
import { ChartCard } from "@/components/ChartCard";
import { useIssuesStore } from "@/store/useIssuesStore";
import { getAssigneeWorkload } from "@/lib/analytics";
import { useMemo } from "react";

const COLORS = [\n  "#3b82f6",\n  "#8b5cf6",\n  "#ec4899",\n  "#f97316",\n  "#14b8a6",\n  "#6366f1",\n  "#ef4444",\n  "#22c55e",\n  "#a855f7",\n  "#06b6d4",\n];\n\nconst CustomTooltip = ({ active, payload }: any) => {\n  if (active && payload && payload.length) {\n    const data = payload[0].payload;\n    return (\n      <div className="rounded-lg border border-gray-200 bg-white px-3 py-2 shadow-lg dark:border-gray-700 dark:bg-gray-800">\n        <p className="font-medium text-gray-900 dark:text-gray-100">{data.name}</p>\n        <p className="text-sm text-gray-500 dark:text-gray-400">Open: {data.open}</p>\n        <p className="text-sm text-gray-500 dark:text-gray-400">Closed: {data.closed}</p>\n        <p className="text-sm text-gray-500 dark:text-gray-400">Total: {data.total}</p>\n      </div>\n    );\n  }\n  return null;\n};\n\nexport function AssigneeBarChart() {\n  const { issues } = useIssuesStore();\n\n  const data = useMemo(() => {\n    return getAssigneeWorkload(issues).slice(0, 10);\n  }, [issues]);\n\n  if (issues.length === 0 || data.length === 0) {\n    return (\n      <ChartCard title="Workload by Assignee" subtitle="Open vs closed issues">\n        <div className="flex h-full items-center justify-center text-sm text-gray-500 dark:text-gray-400">\n          No assignee data available\n        </div>\n      </ChartCard>\n    );\n  }\n\n  return (\n    <ChartCard title="Workload by Assignee" subtitle="Top 10 assignees by total issues">\n      <ResponsiveContainer width="100%" height="100%">\n        <BarChart data={data} layout="vertical" margin={{ left: 100 }}>\n          <CartesianGrid\n            strokeDasharray="3 3"\n            horizontal={false}\n            stroke="#e5e7eb"\n            dark stroke="#374151"\n          />\n          <XAxis type="number" stroke="#6b7280" fontSize={12} />\n          <YAxis\n            type="category"\n            dataKey="name"\n            stroke="#6b7280"
            fontSize={11}
            width={90}
            tickFormatter={(value) => {\n              if (value.length > 12) return value.substring(0, 12) + "...";\n              return value;\n            }}\n          />\n          <Tooltip content={<CustomTooltip />} />\n          <Legend\n            iconType="circle"\n            iconSize={8}\n            wrapperStyle={{ fontSize: "12px" }}\n          />\n          <Bar dataKey="open" stackId="a" fill="#f59e0b" name="Open" radius={[0, 0, 0, 0]} />\n          <Bar dataKey="closed" stackId="a" fill="#22c55e" name="Closed" radius={[4, 4, 0, 0]} />\n        </BarChart>\n      </ResponsiveContainer>\n    </ChartCard>\n  );\n}